version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build:
      context: .
    image: scrapper
    volumes:
      - .:/scrapper
    command:
      python3.6 main.py
    ports:
      - "8000:8000"
    depends_on:
      - mongo
